# Generated by Django 4.2.3 on 2023-07-15 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostViewRecord',
            new_name='PostViewRecords',
        ),
    ]
